name: XcodeBuild

on: [push, pull_request, workflow_dispatch]

jobs:
  XcodeBuild:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: XcodeBuild
      run: xcodebuild clean test -workspace PeerGC.xcworkspace -scheme PeerGC -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty
